- hosts: 192.168.56.105
  vars_files:
          - slave_vars.yml
  tasks:
          - name: "Creating a directory"
            file:
               state: directory
               path: "{{ directory_path }}"
               
          - name: "Copying hdfs-site.xml"
            copy: 
               src: "{{ hdfs_site }}" 
               dest: "/etc/hadoop"

          - name: "Copying core-site.xml"
            copy:
               src: "{{ core_site }}"
               dest: "/etc/hadoop"

          - name: "Stopping Datanode before we run the file"
            shell: "hadoop-daemon.sh stop datanode"
            ignore_errors: yes
            register: hadoop_stopped

          - name: "Check the output of stopping Hadoop Service"
            debug:
               var: hadoop_stopped.stdout

          - name: "Starting datanode service"
            shell: "hadoop-daemon.sh start datanode"
            register: hadoop_start

          - name: "Check the output of starting Hadoop"
            debug:
               var: hadoop_start.stdout

          - name: "Checking hadoop cluster detail"
            shell: "hadoop dfsadmin -report"
            register: hadoop_report

          - name: "Debugging the Report Collected"
            debug:
               var: hadoop_report.stdout 


